[package]
name = "glicko-mmr"
version = "0.1.0"
edition = "2024"

[dependencies]
clickhouse = { version = "0.13.3", features = ["chrono", "inserter"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.45", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0"
common = { version = "0.1.0", path = "../common" }
tracing = "0.1.41"
clap = { version = "4.5.40", features = ["derive", "env"] }
cached = "0.55.1"
chrono = "0.4.41"
dotenv = "0.15.0"
rayon = "1.10.0"
