[package]
name = "glicko-mmr"
version = "0.1.0"
edition = "2024"

[dependencies]
clickhouse = { version = "0.13.3", features = ["chrono", "inserter"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.45", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0"
common = { version = "0.1.0", path = "../common" }
tracing = "0.1.41"
clap = { version = "4.5.40", features = ["derive", "env"] }
cached = { version = "0.55.1", features = ["async"] }
chrono = "0.4.41"
rayon = "1.10.0"
rand = { version = "0.8.5", optional = true }
serde_json = "1.0.140"
tpe = { version = "0.2.0", optional = true }

[features]
hyper_param_tuner = [ "dep:rand", "dep:tpe" ]

[[bin]]
name = "glicko-mmr"
path = "src/main.rs"

[[bin]]
name = "hyper-param-tuner"
path = "tools/hyper_param_tuner.rs"
