[project]
name = "mmr-calc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "clickhouse-driver>=0.2.9",
    "optuna>=4.4.0",
    "pydantic>=2.11.6",
    "tqdm>=4.67.1",
]
