[target.'cfg(target_os = "linux")']
linker = "clang"
rustflags = [
    "-Clink-arg=-fuse-ld=/usr/bin/mold",
]

# Registry configuration for faster dependency fetching
[registries.crates-io]
protocol = "sparse"

# Network configuration
[net]
git-fetch-with-cli = true
