create table active_matches
(
    start_time                     DateTime CODEC (Delta, ZSTD),
    winning_team                   UInt8,
    match_id                       UInt64 CODEC (Delta, ZSTD),
    players                        Nested(account_id UInt32,
                                       team UInt8,
                                       abandoned bool,
                                       hero_id UInt8),
    lobby_id                       UInt64,
    net_worth_team_0               UInt32,
    net_worth_team_1               UInt32,
    duration_s                     UInt32,
    spectators                     UInt16,
    open_spectator_slots           UInt16,
    objectives_mask_team0          UInt16,
    objectives_mask_team1          UInt16,
    match_mode                     Enum8('Unranked' = 1, 'CoopBot' = 3, 'Tutorial' = 6, 'HeroLabs' = 7, 'PrivateLobby' = 2, 'ServerTest' = 5, 'Ranked' = 4, 'Invalid' = 0),
    game_mode                      Enum8('OneVsOneTest' = 2, 'Normal' = 1, 'Invalid' = 0, 'Sandbox' = 3),
    match_score                    UInt16,
    region_mode                    Enum8('Row' = 0, 'Europe' = 1, 'SEAsia' = 2, 'SAmerica' = 3, 'Russia' = 4, 'Oceania' = 5),
    scraped_at                     DateTime64(3) default now() CODEC (Delta, ZSTD),
    team0_core                     Bool alias bitAnd(objectives_mask_team0, bitShiftLeft(1, 0)) != 0,
    team0_tier1_lane1              Bool alias bitAnd(objectives_mask_team0, bitShiftLeft(1, 1)) != 0,
    team0_tier2_lane1              Bool alias bitAnd(objectives_mask_team0, bitShiftLeft(1, 2)) != 0,
    team0_tier1_lane2              Bool alias bitAnd(objectives_mask_team0, bitShiftLeft(1, 3)) != 0,
    team0_tier2_lane2              Bool alias bitAnd(objectives_mask_team0, bitShiftLeft(1, 4)) != 0,
    team0_tier1_lane3              Bool alias bitAnd(objectives_mask_team0, bitShiftLeft(1, 5)) != 0,
    team0_tier2_lane3              Bool alias bitAnd(objectives_mask_team0, bitShiftLeft(1, 6)) != 0,
    team0_tier1_lane4              Bool alias bitAnd(objectives_mask_team0, bitShiftLeft(1, 7)) != 0,
    team0_tier2_lane4              Bool alias bitAnd(objectives_mask_team0, bitShiftLeft(1, 8)) != 0,
    team0_titan                    Bool alias bitAnd(objectives_mask_team0, bitShiftLeft(toUInt16(1), 9)) != 0,
    team0_titan_shield_generator_1 Bool alias bitAnd(objectives_mask_team0, bitShiftLeft(toUInt16(1), 10)) != 0,
    team0_titan_shield_generator_2 Bool alias bitAnd(objectives_mask_team0, bitShiftLeft(toUInt16(1), 11)) != 0,
    team0_barrack_boss_lane1       Bool alias bitAnd(objectives_mask_team0, bitShiftLeft(toUInt16(1), 12)) != 0,
    team0_barrack_boss_lane2       Bool alias bitAnd(objectives_mask_team0, bitShiftLeft(toUInt16(1), 13)) != 0,
    team0_barrack_boss_lane3       Bool alias bitAnd(objectives_mask_team0, bitShiftLeft(toUInt16(1), 14)) != 0,
    team0_barrack_boss_lane4       Bool alias bitAnd(objectives_mask_team0, bitShiftLeft(toUInt16(1), 15)) != 0,
    team1_core                     Bool alias bitAnd(objectives_mask_team1, bitShiftLeft(toUInt16(1), 0)) != 0,
    team1_tier1_lane1              Bool alias bitAnd(objectives_mask_team1, bitShiftLeft(toUInt16(1), 1)) != 0,
    team1_tier2_lane1              Bool alias bitAnd(objectives_mask_team1, bitShiftLeft(toUInt16(1), 2)) != 0,
    team1_tier1_lane2              Bool alias bitAnd(objectives_mask_team1, bitShiftLeft(toUInt16(1), 3)) != 0,
    team1_tier2_lane2              Bool alias bitAnd(objectives_mask_team1, bitShiftLeft(toUInt16(1), 4)) != 0,
    team1_tier1_lane3              Bool alias bitAnd(objectives_mask_team1, bitShiftLeft(toUInt16(1), 5)) != 0,
    team1_tier2_lane3              Bool alias bitAnd(objectives_mask_team1, bitShiftLeft(toUInt16(1), 6)) != 0,
    team1_tier1_lane4              Bool alias bitAnd(objectives_mask_team1, bitShiftLeft(toUInt16(1), 7)) != 0,
    team1_tier2_lane4              Bool alias bitAnd(objectives_mask_team1, bitShiftLeft(toUInt16(1), 8)) != 0,
    team1_titan                    Bool alias bitAnd(objectives_mask_team1, bitShiftLeft(toUInt16(1), 9)) != 0,
    team1_titan_shield_generator_1 Bool alias bitAnd(objectives_mask_team1, bitShiftLeft(toUInt16(1), 10)) != 0,
    team1_titan_shield_generator_2 Bool alias bitAnd(objectives_mask_team1, bitShiftLeft(toUInt16(1), 11)) != 0,
    team1_barrack_boss_lane1       Bool alias bitAnd(objectives_mask_team1, bitShiftLeft(toUInt16(1), 12)) != 0,
    team1_barrack_boss_lane2       Bool alias bitAnd(objectives_mask_team1, bitShiftLeft(toUInt16(1), 13)) != 0,
    team1_barrack_boss_lane3       Bool alias bitAnd(objectives_mask_team1, bitShiftLeft(toUInt16(1), 14)) != 0,
    team1_barrack_boss_lane4       Bool alias bitAnd(objectives_mask_team1, bitShiftLeft(toUInt16(1), 15)) != 0,
    compat_version                 Nullable(UInt32),
    ranked_badge_level             Nullable(UInt32),
    game_mode_version              Nullable(Int32)
)
    engine = MergeTree PRIMARY KEY match_id
        ORDER BY match_id
        SETTINGS index_granularity = 8192, auto_statistics_types = 'tdigest, minmax, uniq, countmin';
