name: docker-image-active-matches-scraper

on:
  workflow_dispatch:
  push:
    branches:
    - 'master'
    paths:
    - 'active-matches-scraper/**'
    - 'common/**'
    - 'Dockerfile'
    - 'Cargo.{toml,lock}'

permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  docker:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/build-push-action@v6
      with:
        platforms: linux/arm64
        push: true
        tags: ghcr.io/${{ github.repository }}/active-matches-scraper:latest
        build-args: EXE_NAME=active-matches-scraper
        cache-from: type=gha
        cache-to: type=gha,mode=max
